### PR TITLE
Use the correct queue for processing MessageEvents

### LINKED ISSUE #25: actionlib 1.11.1 has threading issues not present in earlier versions
Occurs with both 1.11.0 and 1.11.0 -- I presume this is part of the removal of __connection_header, but I haven't fully tracked it down. Opening a ticket in the hopes that someone might just have the answer, otherwise I'll keep digging:

Usage:
- Create a SimpleActionClient with spin_thread=True.
- Call waitForServer with no timeout

Expected Result:
- Connection will be made, and program will continue. This works under hydro, with the same exact code.

What happens:
- We sit forever, queue fills up, but nothing is processed:
- isServerConnected messages continue forever.

```
[DEBUG] [1399620430.065839543]: Spinning up a thread for the SimpleActionClient
[DEBUG] [1399620430.070667607]: Publisher update for [/arm_controller/follow_joint_trajectory/status]: http://ubr1:40107/,  already have these connections: 
[DEBUG] [1399620430.070875230]: Began asynchronous xmlrpc connection to [ubr1:40107]
[DEBUG] [1399620430.075727524]: Publisher update for [/arm_controller/follow_joint_trajectory/feedback]: http://ubr1:40107/,  already have these connections: 
[DEBUG] [1399620430.075954797]: Began asynchronous xmlrpc connection to [ubr1:40107]
[DEBUG] [1399620430.080663252]: Publisher update for [/arm_controller/follow_joint_trajectory/result]: http://ubr1:40107/,  already have these connections: 
[DEBUG] [1399620430.081235731]: Began asynchronous xmlrpc connection to [ubr1:40107]
[DEBUG] [1399620430.398686998]: Incoming queue full for topic "/arm_controller/follow_joint_trajectory/status".  Discarding oldest message (current queue size [0])
[DEBUG] [1399620430.833689019]: isServerConnected: Didn't receive status yet, so not connected yet
[DEBUG] [1399620431.333864630]: isServerConnected: Didn't receive status yet, so not connected yet
```

Now the interesting part:
- If I start an AsyncSpinner, everything works perfectly.

My theory, untested, is that the change to using ros::MessageEvent has moved the messages outside of the callback_queue processed by the simple action client's thread. @dirk-thomas Does this sound remotely possible?

### PR DESCRIPTION
**Pull request by esteve**
Use ActionClient's callback queue instead of the global one

Fixes #25

### CODE REVIEW

**Comment by wjwwood** [comment]
+1

**Comment by tfoote** [comment]
+1

**Comment by dirk-thomas** [comment]
+1

**Comment by dirk-thomas** [comment]
@esteve You might want to wait with the patch release until a new version of bloom is released.

**Pull request merged**
