### PR TITLE
Assertions should not be in any non-development  code

### PR DESCRIPTION
**Pull request by pbeeson**
actionlib is too essential and low-level to have assertions throughout.    I have hit at least one of the these assertions on two different occasions.  While, ultimately it would be great to debug why these assertions can sometimes fail, it is also clear that any production robot system shouldn't just stop due to errors that seem pretty benign.

Issue #67 discusses the assertions in greater detail.
connects to #67

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Sorry for not replying to this earlier. Thanks @pbeeson for reporting and investigating this. I agree that a single assert should not be the result of going through this code path. I'll review this soon and get back to you.

Side question out of curiosity: any particular reason you are not building your production code in Release mode?

**Comment by pbeeson** [comment]
No reason why we aren't other than the fact that  I didn't realize that asserts got turned off on Release code. 

If asserts were ignored in some of the situations, the code wouldn't return 'false' or similar as expected, and wouldn't have printed any ROS messages to logs.  So I think that even a Release build would not be adequate to see and try to diagnose.   

BTW, still haven't diagnosed but I've seen this assertion multiple times over multile > 1 week runs.  My "fixes" that just log errors should trigger at some point in the near future and when they do, I'll report.

**Comment by pbeeson** [comment]
So maybe the right thing to do is to keep my ROS_ERROR message and the asserts but build as Release?

**Comment by mikaelarguedas** [comment]
Yeah I think that is a good alternative. We still need to figure out if in some cases it should either throw or return a specific code. The return values you added look good to me so far but I didn't have time to look closely at which scenarios can result in these code paths.  That's why I've been holding this for now. Your report will be very valuable to trace down why these get triggered.

**Comment by pbeeson** [comment]
Ok. Yeah I have no clue right now why this throws the assertion, but my
guess is a race condition similar to the last I found. But unlike the
previous one this one is much harder to reproduce.

**Comment by pbeeson** [comment]
Any chance you might reexamine this.  I fully support your decision to add the commented out assertions back in; however, for a Release build where these assertions may be ignored then there still needs to be sane return values for these functions so that null pointers aren't accessed.  I have personally hit these assertions on rare occasions when running for weeks and months on end, and I can varify that the fixes I have included seem to allow my software to continue without incident.

**Comment by mikaelarguedas** [comment]
@pbeeson Thanks for the reminder, I'll definitely look into merging this before the next sync. Thanks again for investigating the issue.

**Comment by mikaelarguedas** [comment]
closing in favor of #80

**Pull request closed without merging**
