### PR TITLE
Improved the const-correctness of some actionlib classes.

### PR DESCRIPTION
**Pull request by RobertBlakeAnderson**
I improved the const-correctness of certain classes. This was motivated by a need to call SimpleActionClient::getResult() and SimpleActionClient::getState() inside a const method on my end.

More improvement can probably be done in this area, however I did enough to fix my specific issue.

### CODE REVIEW

**Comment by RobertBlakeAnderson** [comment]
Looks like the checks are failing simply because the check server is running too slowly. Not sure what I can do about that.

**Comment by mikaelarguedas** [comment]
The Kinetic failure was there before and is not impacted by this PR. I wanted to fix it before merging others PRs but I think we shouldn't delay more fixes/cleanup PRs for the sake of this flaky test.
The Jade failure seems to be a timeout issue indeed. We could bump the max time for this test but I'll investigate (and keep you updated) to see why it never appeared before.

Thanks for your patience and contribution.

**Comment by mikaelarguedas** [comment]
@ros-pull-request-builder retest this please

**Comment by mikaelarguedas** [comment]
merging this now that tests are passing. Thanks!

**Pull request merged**
