### PR TITLE
Change boost::posix_time::milliseconds init to uint64_t

### LINKED ISSUE #104: boost::posix_time::milliseconds does not allow float point value initialization
With recent release of the Boost Library, boost::posix_time no longer permit initialize a milliseconds/microseconds with a float point value. This broke some of the packages of ROS, and 'actionlib' is one that's been affected. Other packages being affected include 'rostime' and 'laser_assembler'.

I'm opening this issue here hoping someone could fix it for the good of all people.

I encountered this issue when compiling ROS on my macOS box, which has Boost-1.67.0. And I've fixed them manually, but found it tedious to fork & pull request those fixes. If there is indeed a need to do so, I might do it in the future.

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Fixes #104

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Thanks @Tobias-Fischer for adressing this.

boost 1.67 indeed requires an integer to be passed: https://github.com/boostorg/date_time/blob/8e1f2be36027c007ce6d06e0674576a3794829a5/include/boost/date_time/time_duration.hpp#L286

casting to `int64_t` works from 1.54 to 1.67: https://github.com/boostorg/date_time/blob/9bdee756083a150221170d1c097eb972a6b09a49/include/boost/date_time/time_duration.hpp#L279
so this can be merged in this branch :+1:

**Comment by mikaelarguedas** [comment]
Actually form my previous comment and the fact that ROS Duration are also using signed values, it seems that using `int64_t` instead of `uint64_t` would be preferred to keep the semantic identical.
What do you think ?

**Comment by Tobias-Fischer** [comment]
Hi,
I'm not sure whether to use `int64_t` or `uint64_t`. Logically (at least to me), a wait with a negative time does not make sense. But I am not familiar with the code at all, so please feel free to use whichever one you prefer. You should have write access to my branch to do any required changes.

Best, Tobi

**Review by mikaelarguedas — APPROVED** [review]
Lgtm, thanks @Tobias-Fischer

**Pull request merged**
