### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by mgrrx**
Partially generated with the help of 2to3.
Only tested with python3

### CODE REVIEW

**Comment by wolfv** [comment]
Shouldn't this be a little more graceful so that Python 2 also continues to work?

E.g. check if python3 and then import from `io` or check if python 2 and keep the `from __future__ import ... ` statements.

**Comment by mgrrx** [comment]
- The io module also exists for python 2, so it's still working with python 2 (https://docs.python.org/2/library/io.html).
- the future imports for the print function can easily be removed as there are only 2 print statements with a single argument:

**Comment by mgrrx** [comment]
and the with_statement future import is obsolete since Python 2.6.

**Comment by wolfv** [comment]
Awesome! Sorry for my comments in that case. I'll use your patch in my conda-recipe for ROS melodic as it will use Python 3 by default.

**Review by mjcarroll — APPROVED** [review]
Looks good to me.  I adjusted this to target `noetic`, but it could be potentially backported if needed.

**Pull request merged**
